version: 3

includes:
  # local:backend:
  #   taskfile: ./tasks/backend/local.yaml

  # local:frontend:
  #   taskfile: ./tasks/frontend/local.yaml

  container:backend:
    taskfile: ./tasks/backend/container.yaml

  container:frontend:
    taskfile: ./tasks/frontend/container.yaml

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  setup:
    desc: Set up develop environment
    cmds:
      - mise install
      - direnv allow

  # ---------------------------------------------------------
  # Public API (You only need to run these)
  # ---------------------------------------------------------
  build:
    desc: "Build apps. Usage: task build [MODE=local|container] (default: container)"
    vars:
      MODE: '{{default "container" .MODE}}'
    cmds:
      - task: '{{.MODE}}:build'

  run:
    desc: "Run apps. Usage: task run [MODE=local|container] (default: container)"
    vars:
      MODE: '{{default "container" .MODE}}'
    cmds:
      - task: '{{.MODE}}:run'

  clean:
    desc: "Clean up residual processes. Usage: task clean [MODE=local|container]"
    vars:
      MODE: '{{default "container" .MODE}}'
    cmds:
      - task: '{{.MODE}}:clean'

  # ---------------------------------------------------------
  # Internal Implementation
  # ---------------------------------------------------------
  local:build:
    internal: true
    cmds:
      - task: "local:backend:build"
      - task: "local:frontend:build"

  local:run:
    internal: true
    cmds:
      - overmind start

  local:clean:
    internal: true
    desc: "Clean up residual local processes"
    cmds:
      - pkill -f "nginx|api|vite" || true

  # ---------------------------------------------------------
  # Internal Implementations
  # ---------------------------------------------------------
  container:build:
    internal: true
    cmds:
      - docker compose build

  container:run:
    internal: true
    cmds:
      - docker compose up

  container:clean:
    internal: true
    desc: "Clean up residual container"
    cmds:
      - docker compose down
