version: 3

includes:
  migration:
    taskfile: ./src/backend/taskfile.yaml

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  setup:
    desc: Set up develop environment
    cmds:
      - mise install

  build:
    cmds:
      - docker compose build

  run:
    cmds:
      - docker compose up

  stop:
    desc: "Clean up residual container"
    cmds:
      - docker compose down

  remove_database:
    desc: Remove database
    cmds:
      - docker compose down -v
