# worker_processes  1;
# pid /var/run/nginx.pid;
# events {
#     worker_connections  1024;
# }

# env ENV;
# env URL_BACKEND;
# env URL_FRONTEND;

# http {
#     include       mime.types;
#     default_type  application/octet-stream;

#     access_log stdout;
#     error_log  stderr;

#     lua_package_path "/usr/local/openresty/lualib/?.lua;/etc/nginx/lua/?.lua;;";

#     resolver 127.0.0.11 169.254.169.254 valid=30s;

#     server {
#     listen 8080;

#     location /api/ {
#         set $target_url '';
#         access_by_lua_block {
#             local auth = require("auth")
#             ngx.var.target_url = auth.setup_proxy("URL_BACKEND")
#         }

#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header Host $proxy_host;

#         proxy_pass $target_url$request_uri;
#     }

#     location / {
#         set $target_url '';
#         access_by_lua_block {
#             local auth = require("auth")
#             ngx.var.target_url = auth.setup_proxy("URL_FRONTEND")
#         }

#         proxy_set_header Host $proxy_host;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";

#         proxy_pass $target_url$request_uri;
#     }
# }
# }

worker_processes  1;
pid /var/run/nginx.pid;
events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    access_log stdout;
    error_log  stderr;

    # ハードコード時は resolver は不要ですが、念のため残します
    resolver 169.254.169.254 valid=30s;

    server {
        listen 8080;

        # --- Backend (API) ---
        location /api/ {
            # 実際のアドレスを直書き（末尾に / は付けない）
            proxy_pass https://app-portfolio-backend-dev-442469161656.asia-northeast1.run.app$request_uri;

            # Cloud Runがリクエストを識別するために必須のHostヘッダー
            proxy_set_header Host app-portfolio-backend-dev-442469161656.asia-northeast1.run.app;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # --- Frontend ---
        location / {
            # 実際のアドレスを直書き
            proxy_pass https://app-portfolio-frontend-dev-442469161656.asia-northeast1.run.app$request_uri;

            # Cloud Runがリクエストを識別するために必須のHostヘッダー
            proxy_set_header Host app-portfolio-frontend-dev-442469161656.asia-northeast1.run.app;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
