worker_processes  1;
pid /var/run/nginx.pid;
events {
    worker_connections  1024;
}

env ENV;
env URL_BACKEND;
env URL_FRONTEND;

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log stdout;
    error_log  stderr;

    lua_package_path "/usr/local/openresty/lualib/?.lua;/etc/nginx/lua/?.lua;;";

    resolver 127.0.0.11 169.254.169.254 valid=30s;

    server {
    listen 8080;

    location /api/ {
        set $target_url '';
        access_by_lua_block {
            local auth = require("auth")
            ngx.var.target_url = auth.setup_proxy("URL_BACKEND")
        }

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $proxy_host;

        proxy_pass $target_url$request_uri;
    }

    location / {
        set $target_url '';
        access_by_lua_block {
            local auth = require("auth")
            ngx.var.target_url = auth.setup_proxy("URL_FRONTEND")
        }

        proxy_set_header Host $proxy_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass $target_url$request_uri;
    }
}
}
