version: 3

tasks:
  run:
    desc: Run the frontend development server
    dir: "{{.ROOT_DIR}}/src/frontend"
    cmds:
    - cmd: docker run -p {{.PORT_FRONTEND}}:80 app-frontend

  build:
    desc: Build the frontend for production
    dir: "{{.ROOT_DIR}}/src/frontend"
    cmds:
    - cmd: docker build -t app-frontend .
