version: 3

tasks:
  build:
    desc: Build the frontend for production
    dir: "{{.ROOT_DIR}}/src/frontend"
    cmds:
      - npm run build

  run:
    desc: Run the frontend development server
    dir: "{{.ROOT_DIR}}/src/frontend"
    cmds:
      - npm run dev
