version: 3

tasks:
  build:
    desc: Build the server.
    dir: "{{.ROOT_DIR}}/src/proxy"
    cmds:
      - mkdir -p bin
      - go build -o bin/api main.go

  run:
    desc: Run the server locally.
    dir: "{{.ROOT_DIR}}/src/proxy"
    vars:
      PORT: '{{default "8081" .PORT}}'
    cmds:
      - task: build
      - PORT={{.PORT_BACKEND}} ./bin/api
