version: 3

tasks:
  build:
    desc: Build the container image.
    dir: "{{.ROOT_DIR}}/src/backend"
    cmds:
    - cmd: docker build -t app-backend .

  run:
    desc: Run the server in Container.
    dir: "{{.ROOT_DIR}}/src/backend"
    cmds:
    - cmd: docker run -p {{.PORT_BACKEND}}:8080 app-backend
