version: 3

tasks:
  build:
    desc: Build the container image.
    dir: "{{.ROOT_DIR}}/src/backend"
    cmds:
    - cmd: container build -t app-backend .
      platforms: [darwin]
    - cmd: docker build -t app-backend .
      platforms: [linux]

  run:
    desc: Run the server in Container.
    dir: "{{.ROOT_DIR}}/src/backend"
    cmds:
    - cmd: container run -p {{.PORT_BACKEND}}:8080 app-backend
      platforms: [darwin]
    - cmd: docker run -p {{.PORT_BACKEND}}:8080 app-backend
      platforms: [linux]
