name: Deploy to Cloud Run

on:
  push:
    branches: [ "main", "develop"]

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/job_ci.yaml

  push:
    needs: [ ci ]
    uses: ./.github/workflows/job_deploy.yaml
